# Generated by Django 4.2.6 on 2023-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myContact',
            fields=[
                ('serial_no', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=17)),
                ('address', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=30)),
            ],
        ),
    ]
