# Generated by Django 4.2.6 on 2023-10-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='serial_no',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
