# Generated by Django 4.2.6 on 2023-10-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_mycontact_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='serial_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
